### ISSUE TITLE
Item titles appearing incorrectly

### ISSUE THREAD

**Issue by dsgnr** [Avatar4eg/flarum-ext-share-social#2]
I am getting a strange issue with this extension where the labels are appearing as something else. For example, the settings page pop up, is showing `avatar4eg-share-social.admin.settings.model_title` for example. This is the same case across the whole extension. 

Any ideas on how to resolve this?

**Comment by Avatar4eg** [comment]
Looks like locale files not loaded.
Could you check files in vendor/avatar4eg/share-social/locale?
And describe your configuration (flarum/php version and ext installed).

**Comment by dsgnr** [comment]
Hello,

Inside `/vendor/avatar4eg/flarum-ext-share-social/locale` I have an en.yml, es.yml and ru.yml

My config is as follows:
Debian 8 (Jessie)
Flarum 0.1.0-beta.5.
Nginx
PHP7
MariaDB

Thanks

**Comment by dsgnr** [comment]
To confirm, this was an issue with Cloudflares cache not clearing correctly. Despite putting it in development mode and clearing the cache manually. Thank you again.
