### ISSUE TITLE
JS errors

### ISSUE THREAD

**Issue by angristan** [Avatar4eg/flarum-ext-share-social#5]
So when I enable the extension I get thoses errors : 
![screenshot_09-02-2017_b 97t5rpyq](https://cloud.githubusercontent.com/assets/11699655/22778970/34369114-eeb9-11e6-9c91-4944c4e30169.png)

And when I click on settings : 
![screenshot_09-02-2017_b jsepm5l5](https://cloud.githubusercontent.com/assets/11699655/22778981/3b8c5d72-eeb9-11e6-8e2d-f3d9b97ad897.png)

I use Cloudflare, FYI.

**Comment by Leinad4Mind** [comment]
I'm getting the same error. I don't use Cloudflare, neither anything similar to it.
